package bibtex;

public enum Fields {
    ADRESS, AUTHOR, BOOKTITLE, CHAPTER, EDITION, EDITOR, HOWPUBLISHED, INSTITUTION, JOURNAL, KEY,
    MONTH, NOTE, NUMBER, ORGANIZATION, PAGES, PUBLISHER, SCHOOL, SERIES,
    TITLE, TYPE, VOLUME, YEAR

}
